### ISSUE TITLE
New forge release?

### ISSUE THREAD

**Issue by rlaban** [sbadia/puppet-bird#3]
Are there any plans to release a newer version to the Puppet Forge?

**Comment by sbadia** [comment]
Hi here!

Sorry for the delay on this one…

**Comment by sbadia** [comment]
Hi @rlaban,
It should be ok right now :)
https://forge.puppet.com/sbadia/bird (fixed by https://github.com/sbadia/puppet-bird/commit/40f6b944770a013687ca0db2e966e025d62733cf)
